name = "radiosmoldova-web"
main = ".output/server/index.mjs"
compatibility_date = "2026-03-30"
workers_dev = true
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".output/public"
binding = "ASSETS"
